### ISSUE TITLE
Issue about check port in referrer

### ISSUE THREAD

**Issue by NamPNQ** [onfido/onfido-node#76]
I think this is not the good place to post this issue, but I don't know where is better, because it's in the backend 

Follow the docs: https://documentation.onfido.com/#generate-sdk-token

I generate a token with `referrer:*://*.mydomain.com/*`

It should work with referrer `http://dev.mydomain.com:3005` instead of return 401 error

**Comment by onfido-website-team** [comment]
Hi @NamPNQ 
I'm not quite sure if I understood the issue. 
Are you saying you used something like:

```
{
     "applicant_id": "<APPLICANT_ID>",
     "referrer": "*://*.mydomain.com/*",
 }'
```
And It worked. However, when you used the following, you got a 401 error? 
```
{
     "applicant_id": "<APPLICANT_ID>",
     "referrer": "http://dev.mydomain.com:3005",
 }'
```
Maybe the issue is due to the last forward slash. Please try to use:
` "referrer": "http://dev.mydomain.com:3005/"` 

Another observation:
You must use a site referrer policy that lets the Referer header be sent. If your policy does not allow this (e.g. Referrer-Policy: no-referrer), then you'll receive a 401 bad_referrer error when trying to use the Web SDK.

More information on https://documentation.onfido.com/#the-referrer-argument

**Comment by NamPNQ** [comment]
Hello @onfido-website-team 

You can reproduce by flow this:
1. Generate the token with config `referrer:*://*.mydomain.com/*`
2. Use this token in http://dev.mydomain.com:3005/

It should work, but I got 401 error

I already checked referrer in header, it's corrected

**Comment by onfido-website-team** [comment]
Hi @NamPNQ 

Thank you for clarifying the issue. When creating the SDK token, you should pass ` * ` in the referrer.
`"referrer": "*"` 

Then it will allow you to use a referrer with port (http://dev.mydomain.com:3005/)

I hope this information helps. Please let me know if you require further assistance.

**Comment by NamPNQ** [comment]
@onfido-website-team The purpose of use referrer config is guarantees that other malicious websites cannot reuse the token in case it is lost. So set to `*` is not the good idea?
